apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: grafana
    repo: https://grafana.github.io/helm-charts
    releaseName: grafana
    namespace: grafana
    version: 9.3.1
    valuesInline:
      testFramework:
        enabled: false
      rbac:
        namespaced: true
      admin:
        existingSecret: grafana-credentials
        userKey: username
        passwordKey: password