apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: istiod
spec:
  source:
    path: artifacts/infrastructure/istiod
  ignoreDifferences:
    - group: admissionregistration.k8s.io
      kind: ValidatingWebhookConfiguration
      name: istio-validator-istio-system
      jsonPointers:
        - /webhooks/0/clientConfig/caBundle
        - /webhooks/0/failurePolicy
