---
- name: Recover controller kubeconfig from first K3s server
  hosts: server[0]
  become: true
  tasks:
    - name: Export controller kubeconfig
      ansible.builtin.include_role:
        name: k3s_server
        tasks_from: export_kubeconfig.yml
