apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: homelab-private
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: homelab-private
  source:
    repoURL: https://github.com/nandiheath/homelab-private.git
    targetRevision: main
    path: artifacts/application/application-app-of-apps
    directory:
      recurse: true
      include: '{*.yaml,*.yml}'
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
